name: Unit test for MathOps.py

on:
  push:
    branches:
    - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run script
      run: python TestMathOps.py
